# ============================================================
# PetroVision — Batch & Production Models
# ============================================================

from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, Text, JSON,
    ForeignKey,
)
from sqlalchemy.orm import relationship
from app.core.database import Base


class Batch(Base):
    """
    Production batch — a discrete unit of production.
    """
    __tablename__ = "batches"

    id = Column(Integer, primary_key=True, index=True)
    process_id = Column(Integer, ForeignKey("chemical_processes.id"), nullable=False)

    batch_number = Column(String(30), unique=True, nullable=False, index=True)  # "MA-2026-0217-001"
    status = Column(String(20), default="PLANNED")
    # States: PLANNED, IN_PROGRESS, COMPLETED, APPROVED, REJECTED

    # Timing
    planned_start = Column(DateTime(timezone=True), nullable=True)
    actual_start = Column(DateTime(timezone=True), nullable=True)
    actual_end = Column(DateTime(timezone=True), nullable=True)

    # Feed
    feed_amount_kg = Column(Float, nullable=True)
    feed_material = Column(String(100), nullable=True)

    # Product
    product_amount_kg = Column(Float, nullable=True)
    product_name = Column(String(100), nullable=True)

    # Quality
    purity = Column(Float, nullable=True)  # %
    yield_actual = Column(Float, nullable=True)  # %
    yield_predicted = Column(Float, nullable=True)  # % (ML prediction)
    quality_grade = Column(String(10), nullable=True)  # A, B, C

    # Operating conditions (averages during batch)
    avg_temperature = Column(Float, nullable=True)
    avg_pressure = Column(Float, nullable=True)

    # Operator
    operator_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    notes = Column(Text, nullable=True)

    # Economics
    production_cost = Column(Float, nullable=True)
    revenue = Column(Float, nullable=True)

    # Lab results (JSON)
    lab_results = Column(JSON, nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Relationships
    process = relationship("ChemicalProcess", back_populates="batches")

    def __repr__(self):
        return f"<Batch {self.batch_number} [{self.status}]>"


class ProductionReport(Base):
    """
    Periodic production reports (shift/daily/weekly/monthly).
    """
    __tablename__ = "production_reports"

    id = Column(Integer, primary_key=True, index=True)
    process_id = Column(Integer, ForeignKey("chemical_processes.id"), nullable=False)

    report_type = Column(String(20), nullable=False)  # shift, daily, weekly, monthly
    period_start = Column(DateTime(timezone=True), nullable=False)
    period_end = Column(DateTime(timezone=True), nullable=False)

    # KPIs
    total_production_kg = Column(Float, default=0.0)
    total_feed_kg = Column(Float, default=0.0)
    avg_yield = Column(Float, nullable=True)
    avg_purity = Column(Float, nullable=True)
    oee = Column(Float, nullable=True)  # Overall Equipment Effectiveness %
    uptime_hours = Column(Float, nullable=True)
    downtime_hours = Column(Float, nullable=True)

    # Economics
    total_cost = Column(Float, nullable=True)
    total_revenue = Column(Float, nullable=True)
    margin = Column(Float, nullable=True)

    # Alarms
    total_alarms = Column(Integer, default=0)
    critical_alarms = Column(Integer, default=0)

    # Generated by
    generated_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Full report data (JSON for flexibility)
    data = Column(JSON, nullable=True)

    def __repr__(self):
        return f"<Report {self.report_type} {self.period_start}>"
